# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    pkgs,
    modulesPath,
    ...
}: {
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/8123f2fa-2e4b-4639-ae7f-7bd3015303f3";
        fsType = "ext4";
    };

    fileSystems."/mnt/drive2" = {
        device = "/dev/disk/by-uuid/3b7b5fed-297e-4c7f-8007-22442904473f";
        fsType = "ext4";
    };

    swapDevices = [
        {device = "/dev/disk/by-uuid/0e35e063-1dae-4b7b-a4b5-030fb8f13213";}
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
